/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as LanguagesRouteImport } from './routes/languages'
import { Route as CreateBookRouteImport } from './routes/create-book'
import { Route as BackupsRouteImport } from './routes/backups'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TermsIndexRouteImport } from './routes/terms/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as BooksIndexRouteImport } from './routes/books/index'
import { Route as TermsTagsRouteImport } from './routes/terms/tags'
import { Route as TermsCreateNewRouteImport } from './routes/terms/create-new'
import { Route as TermsTermIdRouteImport } from './routes/terms/$termId'
import { Route as SettingsShortcutsRouteImport } from './routes/settings/shortcuts'
import { Route as BooksBookIdRouteRouteImport } from './routes/books/$bookId/route'
import { Route as BooksBookIdPagesPageNumIndexRouteImport } from './routes/books/$bookId/pages.$pageNum/index'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguagesRoute = LanguagesRouteImport.update({
  id: '/languages',
  path: '/languages',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateBookRoute = CreateBookRouteImport.update({
  id: '/create-book',
  path: '/create-book',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupsRoute = BackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsIndexRoute = TermsIndexRouteImport.update({
  id: '/terms/',
  path: '/terms/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsTagsRoute = TermsTagsRouteImport.update({
  id: '/terms/tags',
  path: '/terms/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsCreateNewRoute = TermsCreateNewRouteImport.update({
  id: '/terms/create-new',
  path: '/terms/create-new',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsTermIdRoute = TermsTermIdRouteImport.update({
  id: '/terms/$termId',
  path: '/terms/$termId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsShortcutsRoute = SettingsShortcutsRouteImport.update({
  id: '/settings/shortcuts',
  path: '/settings/shortcuts',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksBookIdRouteRoute = BooksBookIdRouteRouteImport.update({
  id: '/books/$bookId',
  path: '/books/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksBookIdPagesPageNumIndexRoute =
  BooksBookIdPagesPageNumIndexRouteImport.update({
    id: '/pages/$pageNum/',
    path: '/pages/$pageNum/',
    getParentRoute: () => BooksBookIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backups': typeof BackupsRoute
  '/create-book': typeof CreateBookRoute
  '/languages': typeof LanguagesRoute
  '/stats': typeof StatsRoute
  '/books/$bookId': typeof BooksBookIdRouteRouteWithChildren
  '/settings/shortcuts': typeof SettingsShortcutsRoute
  '/terms/$termId': typeof TermsTermIdRoute
  '/terms/create-new': typeof TermsCreateNewRoute
  '/terms/tags': typeof TermsTagsRoute
  '/books': typeof BooksIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/terms': typeof TermsIndexRoute
  '/books/$bookId/pages/$pageNum': typeof BooksBookIdPagesPageNumIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backups': typeof BackupsRoute
  '/create-book': typeof CreateBookRoute
  '/languages': typeof LanguagesRoute
  '/stats': typeof StatsRoute
  '/books/$bookId': typeof BooksBookIdRouteRouteWithChildren
  '/settings/shortcuts': typeof SettingsShortcutsRoute
  '/terms/$termId': typeof TermsTermIdRoute
  '/terms/create-new': typeof TermsCreateNewRoute
  '/terms/tags': typeof TermsTagsRoute
  '/books': typeof BooksIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/terms': typeof TermsIndexRoute
  '/books/$bookId/pages/$pageNum': typeof BooksBookIdPagesPageNumIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backups': typeof BackupsRoute
  '/create-book': typeof CreateBookRoute
  '/languages': typeof LanguagesRoute
  '/stats': typeof StatsRoute
  '/books/$bookId': typeof BooksBookIdRouteRouteWithChildren
  '/settings/shortcuts': typeof SettingsShortcutsRoute
  '/terms/$termId': typeof TermsTermIdRoute
  '/terms/create-new': typeof TermsCreateNewRoute
  '/terms/tags': typeof TermsTagsRoute
  '/books/': typeof BooksIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/terms/': typeof TermsIndexRoute
  '/books/$bookId/pages/$pageNum/': typeof BooksBookIdPagesPageNumIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backups'
    | '/create-book'
    | '/languages'
    | '/stats'
    | '/books/$bookId'
    | '/settings/shortcuts'
    | '/terms/$termId'
    | '/terms/create-new'
    | '/terms/tags'
    | '/books'
    | '/settings'
    | '/terms'
    | '/books/$bookId/pages/$pageNum'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backups'
    | '/create-book'
    | '/languages'
    | '/stats'
    | '/books/$bookId'
    | '/settings/shortcuts'
    | '/terms/$termId'
    | '/terms/create-new'
    | '/terms/tags'
    | '/books'
    | '/settings'
    | '/terms'
    | '/books/$bookId/pages/$pageNum'
  id:
    | '__root__'
    | '/'
    | '/backups'
    | '/create-book'
    | '/languages'
    | '/stats'
    | '/books/$bookId'
    | '/settings/shortcuts'
    | '/terms/$termId'
    | '/terms/create-new'
    | '/terms/tags'
    | '/books/'
    | '/settings/'
    | '/terms/'
    | '/books/$bookId/pages/$pageNum/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BackupsRoute: typeof BackupsRoute
  CreateBookRoute: typeof CreateBookRoute
  LanguagesRoute: typeof LanguagesRoute
  StatsRoute: typeof StatsRoute
  BooksBookIdRouteRoute: typeof BooksBookIdRouteRouteWithChildren
  SettingsShortcutsRoute: typeof SettingsShortcutsRoute
  TermsTermIdRoute: typeof TermsTermIdRoute
  TermsCreateNewRoute: typeof TermsCreateNewRoute
  TermsTagsRoute: typeof TermsTagsRoute
  BooksIndexRoute: typeof BooksIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  TermsIndexRoute: typeof TermsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/languages': {
      id: '/languages'
      path: '/languages'
      fullPath: '/languages'
      preLoaderRoute: typeof LanguagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-book': {
      id: '/create-book'
      path: '/create-book'
      fullPath: '/create-book'
      preLoaderRoute: typeof CreateBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backups': {
      id: '/backups'
      path: '/backups'
      fullPath: '/backups'
      preLoaderRoute: typeof BackupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms/': {
      id: '/terms/'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/': {
      id: '/books/'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms/tags': {
      id: '/terms/tags'
      path: '/terms/tags'
      fullPath: '/terms/tags'
      preLoaderRoute: typeof TermsTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms/create-new': {
      id: '/terms/create-new'
      path: '/terms/create-new'
      fullPath: '/terms/create-new'
      preLoaderRoute: typeof TermsCreateNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms/$termId': {
      id: '/terms/$termId'
      path: '/terms/$termId'
      fullPath: '/terms/$termId'
      preLoaderRoute: typeof TermsTermIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/shortcuts': {
      id: '/settings/shortcuts'
      path: '/settings/shortcuts'
      fullPath: '/settings/shortcuts'
      preLoaderRoute: typeof SettingsShortcutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$bookId': {
      id: '/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof BooksBookIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$bookId/pages/$pageNum/': {
      id: '/books/$bookId/pages/$pageNum/'
      path: '/pages/$pageNum'
      fullPath: '/books/$bookId/pages/$pageNum'
      preLoaderRoute: typeof BooksBookIdPagesPageNumIndexRouteImport
      parentRoute: typeof BooksBookIdRouteRoute
    }
  }
}

interface BooksBookIdRouteRouteChildren {
  BooksBookIdPagesPageNumIndexRoute: typeof BooksBookIdPagesPageNumIndexRoute
}

const BooksBookIdRouteRouteChildren: BooksBookIdRouteRouteChildren = {
  BooksBookIdPagesPageNumIndexRoute: BooksBookIdPagesPageNumIndexRoute,
}

const BooksBookIdRouteRouteWithChildren =
  BooksBookIdRouteRoute._addFileChildren(BooksBookIdRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BackupsRoute: BackupsRoute,
  CreateBookRoute: CreateBookRoute,
  LanguagesRoute: LanguagesRoute,
  StatsRoute: StatsRoute,
  BooksBookIdRouteRoute: BooksBookIdRouteRouteWithChildren,
  SettingsShortcutsRoute: SettingsShortcutsRoute,
  TermsTermIdRoute: TermsTermIdRoute,
  TermsCreateNewRoute: TermsCreateNewRoute,
  TermsTagsRoute: TermsTagsRoute,
  BooksIndexRoute: BooksIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  TermsIndexRoute: TermsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
